config/routes.rb
Rails.application.routes.draw do
  resources :rounds, only: %i[index]
  resources :webpush_notifications, only: %i[create]
  get 'trends', to: 'rounds#trends'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "rounds#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/level_plan.rb
class LevelPlan < ApplicationRecord
  def self.current
    LevelPlan.find_by(year: Date.current.year)
  end

  def total_invitations
    @total_invitations ||= Round.where(draw_at: Date.new(year, 1, 1)...Date.new(year + 1, 1, 1)).sum(:size)
  end
end

app/models/round.rb
class Round < ApplicationRecord
  ROUND_BASE_URL = 'https://www.canada.ca/en/immigration-refugees-citizenship/corporate/mandate/policies-operational-instructions-agreements/ministerial-instructions/express-entry-rounds/invitations.html'
  GET_ROUNDS_JSON_URL = 'https://www.canada.ca/content/dam/ircc/documents/json/ee_rounds_4_en.json'

  attr_accessor :send_notifications_after_save

  after_commit :send_notifications, if: -> { send_notifications_after_save }

  def assign_raw_round(raw_round)
    assign_attributes(
      number: raw_round['drawNumber'],
      name: raw_round['drawName'],
      draw_at: DateTime.parse(raw_round['drawDateTime']),
      size: raw_round['drawSize'].delete(',').to_i,
      minister: raw_round['drawMinister'],
      crs: raw_round['drawCRS'],
      tie_breaking_at: raw_round['drawCutOff']
    )
  end

  def round_url
    ROUND_BASE_URL + "?q=#{number}"
  end

  def notification_message
    {
      title: "🇨🇦 Express Entry Round ##{number}",
      body: "Invitiation issues: #{ActiveSupport::NumberHelper.number_to_delimited(size)}, CRS: #{crs}, Type: #{name}, ",
      data: {
        url: 'https://calmmigration.ca'
      },
      tag: "express-entry-round-#{number}",
      icon: ActionController::Base.helpers.asset_url("logo.png")
    }
  end

  private

  def send_notifications
    WebpushNotification.send_notifications(notification_message)
  end
end

app/models/webpush_notification.rb
class WebpushNotification < ApplicationRecord
  def self.send_notifications(message)
    WebpushNotification.find_each do |notification|
      begin
        notification.send_message(message)
      rescue WebPush::ExpiredSubscription
        notification.destroy
      end
    end
  end

  def send_message(message)
    WebPush.payload_send(
      endpoint: endpoint,
      message: JSON.generate(message),
      p256dh: p256dh,
      auth: auth,
      vapid: {
        public_key: Rails.application.credentials.webpush.public_key,
        private_key: Rails.application.credentials.webpush.private_key
      }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
    @level_plan = LevelPlan.current
    @grid = RoundsGrid.new(grid_params) do |scope|
      scope.page(params[:page]).per(25)
    end
  end

  def trends
    @rounds = Round.all
  end

  protected

  def grid_params
    params.fetch(:rounds_grid, {}).permit!
  end
end

app/controllers/webpush_notifications_controller.rb
class WebpushNotificationsController < ApplicationController
  def create
    webpush_notification = WebpushNotification.find_or_create_by(
      p256dh: params[:keys][:p256dh],
      auth: params[:keys][:auth]
    )
    webpush_notification.update!(endpoint: params[:endpoint])
    render json: { status: :ok }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calmmigration</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Calmmigration checks IRCC website frequently and send you notification when new Express Entry round is announced. You just need to keep calm and wait for notifications.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="manifest" href="/manifest.json">
    <link rel="apple-touch-icon" href="<%= asset_path('webapp-icon.png') %>">
    <link rel="apple-touch-startup-image" href="<%= asset_path('webapp-icon.png') %>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <%= yield :head %>

    <script src="https://kit.fontawesome.com/4335c2f54b.js" crossorigin="anonymous"></script>

    <script>
      window.vapidPublicKey = new Uint8Array(<%= Base64.urlsafe_decode64(Rails.application.credentials.dig(:webpush, :public_key)).bytes %>)
    </script>
  </head>

  <% if Rails.env.production? %>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-G22KQW9X6M"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-G22KQW9X6M');
    </script>
  <% end %>

  <body>
    <%= render 'shared/header' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/rounds/_ios_warning.html.erb
<div
  class="notification is-warning"
  data-controller="ios-warning"
>
  ⚠️ If you are using iOS, you have to use Safari and Add to Home Screen and open this website from the home screen to receive notifications.<br>
  <button
    class="button is-rounded"
    data-action="ios-warning#openModal"
  >
    Tutorial
  </button>
  <div class="modal" data-ios-warning-target="modal">
    <div class="modal-background" data-action="click->ios-warning#closeModal"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Add to Homepage</p>
        <button class="delete" data-action="click->ios-warning#closeModal" aria-label="close"></button>
      </header>
      <section class="modal-card-body">
        <div class="content">
          <h4 class="title">1. Click the <strong>Share</strong> button</h4>
          <%= image_tag 'tutorial-1.png', class: 'tutorial-img' %>
          <h4 class="title">2. Click <strong>Add to Homepage</strong></h4>
          <%= image_tag 'tutorial-2.png', class: 'tutorial-img' %>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/rounds/_round.html.erb
<div id="<%= dom_id round %>">
  <p>
    <strong>Number:</strong>
    <%= round.number %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= round.name %>
  </p>

  <p>
    <strong>Draw at:</strong>
    <%= round.draw_at %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= round.size %>
  </p>

  <p>
    <strong>Minister:</strong>
    <%= round.minister %>
  </p>

  <p>
    <strong>Crs:</strong>
    <%= round.crs %>
  </p>

  <p>
    <strong>Tie breaking at:</strong>
    <%= round.tie_breaking_at %>
  </p>

</div>

app/views/rounds/index.html.erb
<div id="rounds" class="section">
  <div class="columns is-desktop">
    <div class="column is-8 is-offset-2">
      <h2 class="title is-size-4">🇨🇦 Express Entry Rounds</h2>
      <div class="content">
        <p class="is-size-5">
          Keep refreshing IRCC's webpage is bad for your health. Subscribe to receive notifications when a new round is announced.
        </p>
      </div>
      <%= render 'ios_warning' %>
      <div
        id="subscribe-to-rounds"
        class="mb-4"
        data-controller="subscription"
        data-subscription-vapid-public-key-value="<%= Base64.urlsafe_decode64(Rails.application.credentials.dig(:webpush, :public_key)).bytes %>"
        data-subscription-subscribed-value="false"
      >
        <%= button_tag(
          'Subscribe to notifications',
          class: 'button is-success',
          data: {
            'subscription-target': 'button',
            action: 'click->subscription#toggleSubscription'
          })
        %>
      </div>
      <section id="target" class="my-5">
        <div class="is-flex is-justify-content-space-between">
          <div class="label-left">
            <strong>
              <%= @level_plan.year %> Total Invitations / Target:
              <%= ActiveSupport::NumberHelper.number_to_delimited @level_plan.total_invitations %> /
              <%= ActiveSupport::NumberHelper.number_to_delimited @level_plan.target %>
            </strong>
          </div>
          <div class="level-right ml-3">
            source: <%= link_to 'Link', @level_plan.source, target: '_blank' %>
          </div>
        </div>
        <progress class="progress is-primary" value="<%= @level_plan.total_invitations %>" max="<%= @level_plan.target %>"></progress>
      </section>
      <div class="table-container">
        <%= datagrid_table @grid, html: { class: 'table is-striped is-hoverable is-fullwidth' } %>
      </div>
      <%= paginate @grid.assets, window: 2 %>
    </div>
  </div>
</div>

app/views/rounds/trends.html.erb
<% content_for :head do %>
  <%= vite_javascript_tag 'trends.jsx' %>
<% end %>
<div id="app"></div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      The source code of <strong>Calmmigration</strong> is licensed
      <%= link_to 'MIT', 'https://github.com/kevinluo201/calmmigration/blob/main/LICENSE' %>.
    </p>
    <div class="links">
      <%= link_to 'https://github.com/kevinluo201/calmmigration', target: '_blank' do %>
        <span class="icon">
          <i class="fa-brands fa-github fa-2xl"></i>
        </span>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://calmmigration.ca">
      <%= image_tag 'logo.png', class: 'mr-2' %>
      <span class="is-size-4">Calmmigration</span>
    </a>
    <%= link_to 'Rounds', rounds_path, class: 'navbar-item' %>
    <%= link_to 'Trends', '/trends', class: 'navbar-item', data: { turbo: false } %>
  </div>
</nav>